version: '3.4'

services:
  signalrapi:
    image: ${DOCKER_REGISTRY-}signalrapi
    build:
      context: .
      dockerfile: signalrApi/Dockerfile
    ports:
       - "8000:80"
    depends_on:
       - db
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
